### ISSUE TITLE
SyntaxError: await is only valid in async function

### ISSUE THREAD

**Issue by dennisbaum** [Pamblam/mysql-import#25]
Hola,

as part of a npm-build-system i get the following error, if i like to execute your simple example with:

```js
const mysql_import = require('mysql-import');
const mydb_importer = mysql_import.config({
	host: 'localhost',
	user: 'root',
	password: 'root',
	database: 'mysuperdb',
	onerror: err=>console.log(err.message)
});
await mydb_importer.import('mydb.sql');
```

```
await mydb_importer.import('mydb.sql');
^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:1067:16)
    at Module._compile (internal/modules/cjs/loader.js:1115:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

```
2 info using npm@6.13.7
3 info using node@v13.8.0
```

Any idea whats wrong here?
Tnx

**Comment by Pamblam** [comment]
You need to put any `await`-ed functions inside an `async` function.

```
(async ()=>{

    // Put your code here

})();
```

Read more about [async/await](https://javascript.info/async-await).

**Comment by dennisbaum** [comment]
Thx Pablam,

i tried the following:

```js
const restore = async (file) => {
    const mydb_importer = importer.config({
        host: config.server,
        user: config.user,
        password: config.pass,
        database: config.db,
        socketPath: process.env.socketpath,
        onerror: err => console.log(err.message)
    });
    return await mydb_importer.import(file);
}
restore('/mypath/test.sql').then(
    function () {
        console.log('done');
    }
)
```

the config seems to be ok, no error - if i add all needed props.
the socketPath comes from .npmrc (worked fine with mysql-import@1.0.9 in an older project)
Unfortunately the process hangs in the following method: the showloop in the promise is never called?
(the showloop-method was called in the import-method, but not in the importSingleFile-method)

```js
importSingleFile(filename){
        console.log('importSingleFile1',  fs.readFileSync(filename, 'utf8');    
   // log is ok, also the content of the sql-file
        return new Promise(done=>{
	    var queriesString = fs.readFileSync(filename, 'utf8');
            var queries = new queryParser(queriesString).queries;
            console.log('importSingleFile2', queriesString); 
     // did not log, seems the whole promise is not executing
            slowLoop(queries, (q,i,d)=>{
	        try{
		    this.conn.query(q, err=>{
```

any idea what else can be wrong here?
tnx!
