### ISSUE TITLE
empty lines throw error

### ISSUE THREAD

**Issue by theraaz** [Pamblam/mysql-import#3]
Hi, thanks for the package. One small issue, if there are empty lines in mysql file then it throws error. Is there any option to ignore empty lines?
```
Insert ignore into `supe...


Insert ignore into `acco...
```
throws error:
```
ER_EMPTY_QUERY: Query was empty { Error: ER_EMPTY_QUERY: Query was empty
    at Query.Sequence._packetToError (MY_PROJ\node_modules\mysql\lib\protocol\sequences\Sequence.js:52:14)
    at Query.ErrorPacket (MY_PROJ\node_modules\mysql\lib\protocol\sequences\Query.js:77:18)
    at Protocol._parsePacket (MY_PROJ\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (MY_PROJ\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (MY_PROJ\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (MY_PROJ\node_modules\mysql\lib\Connection.js:103:28)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
    --------------------
    at Protocol._enqueue (MY_PROJ\node_modules\mysql\lib\protocol\Protocol.js:145:48)
    at Connection.query (MY_PROJ\node_modules\mysql\lib\Connection.js:208:25)
    at slowLoop (MY_PROJ\node_modules\mysql-import\mysql-import.js:27:10)
    at f (MY_PROJ\node_modules\mysql-import\mysql-import.js:84:3)
    at new Promise (<anonymous>)
    at slowLoop (MY_PROJ\node_modules\mysql-import\mysql-import.js:80:9)
    at items.(anonymous function) (MY_PROJ\node_modules\mysql-import\mysql-import.js:83:35)
    at Query.conn.query.err [as _callback] (MY_PROJ\node_modules\mysql-import\mysql-import.js:30:11)
    at Query.Sequence.end (MY_PROJ\node_modules\mysql\lib\protocol\sequences\Sequence.js:88:24)
    at Query._handleFinalResultPacket (MY_PROJ\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)
    at Query.OkPacket (MY_PROJ\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
    at Protocol._parsePacket (MY_PROJ\node_modules\mysql\lib\protocol\Protocol.js:279:23)
    at Parser.write (MY_PROJ\node_modules\mysql\lib\protocol\Parser.js:76:12)
    at Protocol.write (MY_PROJ\node_modules\mysql\lib\protocol\Protocol.js:39:16)
    at Socket.<anonymous> (MY_PROJ\node_modules\mysql\lib\Connection.js:103:28)
    at Socket.emit (events.js:180:13)
    at Socket.emit (domain.js:421:20)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
  code: 'ER_EMPTY_QUERY',
  errno: 1065,
  sqlMessage: 'Query was empty',
  sqlState: '42000',
  index: 0,
  sql: '\n' }
```

**Comment by Pamblam** [comment]
Hi @theraaz 

There are blank lines in the test file that it builds with, so blank lines can't be the problem. Can you please share with me the `.sql` file so I can figure out the source of this error?

**Comment by theraaz** [comment]
i found the issue, it happens only when there is an empty line at the end of sql file. I'm using IntelliJ Idea and that adds an empty line at the end of every file. when i remove that manually then it works

**Comment by Pamblam** [comment]
Thanks for taking the time to look into that.. It's fixed as of v1.0.9.

**Comment by theraaz** [comment]
thanks @Pamblam for fixing it so quick!

**Comment by Oscarteg** [comment]
I have this same issue

**Comment by Pamblam** [comment]
@Oscarteg - Can you provide sample data? If I can reproduce it I'll fix it.

**Comment by Oscarteg** [comment]
I'll try to recreate it with test data.

**Comment by Oscarteg** [comment]
@Pamblam was a mistake on my end. I'm sorry.

**Comment by Pamblam** [comment]
Thanks for the follow up @Oscarteg - glad you got it sorted!
