### ISSUE TITLE
Access Denied errno: 1045 in MariaDB 10.3.x on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by davidsaulrodriguez** [Pamblam/mysql-import#38]
## Synopsis

I can't seem to get a proper connection with my local database and using valid login credentials.

---

Given my config below, I was wondering what the problem could be.

```javascript
const dotenv = require('dotenv').config();
const Importer = require('mysql-import');
const host = process.env.DB_HOST;
const user = process.env.DB_USER;
const passwd = process.env.DB_PASS;
const importer = new Importer({host, user, passwd});
```

When running the import method, it seems that I can't login and connect with `mysql-import`.

```javascript
importer.import('EMS_DB.sql').then(() => {
  let files_imported = importer.getImported(); 
  console.log(`${files_imported.length} SQL file(s) imported.`);
}).catch(err => {
  console.log(err);
});
```

The error message I get when running my code is:

```shell
david@cx626qd:~/employee-management-system(main)$ npm run createDB

> employee-management-system@0.1.0 createDB /media/david/240GB/sandbox/Homework/employee-management-system
> node createDB

Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'admin'@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    --------------------
    at Protocol._enqueue (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql/lib/Connection.js:116:18)
    at /media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql-import/mysql-import.js:256:15
    at new Promise (<anonymous>)
    at Importer._connect (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql-import/mysql-import.js:250:10)
    at /media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql-import/mysql-import.js:130:16
    at new Promise (<anonymous>)
    at Importer.import (/media/david/240GB/sandbox/Homework/employee-management-system/node_modules/mysql-import/mysql-import.js:128:10)
    at Object.<anonymous> (/media/david/240GB/sandbox/Homework/employee-management-system/createDB.js:17:16) {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user 'admin'@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
```

When logging into MySQL / MariaDB locally I have no issues whatsoever with the correct credentials in my `.env` file.

Also, when checking the authentication type with:

```mysql
SELECT user,plugin,host FROM mysql.user where user like '%admin%';
```
I receive the following output:

```shell
+-------+-----------------------+-----------+
| user  | plugin                | host      |
+-------+-----------------------+-----------+
| admin | mysql_native_password | localhost |
+-------+-----------------------+-----------+
1 row in set (0.000 sec)
```

When double checking against the error and running:

```mysql
SHOW GRANTS FOR CURRENT_USER();
```

I receive the following output:

```shell
+-----------------------------------------------------------------------------------------------------------------------------------------+
| Grants for admin@localhost                                                                                                              |
+-----------------------------------------------------------------------------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO `admin`@`localhost` IDENTIFIED BY PASSWORD 'Hash-Removed' WITH GRANT OPTION |
+-----------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.000 sec)
```

## Current OS
KDE Neon 5.20.5 - based on Ubuntu 20.04 LTS

## Database
**MariaDB**
Server version: 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04

## NodeJS version
**v14.15.4** (npm v6.14.10)

## mysql-import version
5.0.20

**Comment by Pamblam** [comment]
Hey! The constructor requires a 'password' property, you're giving it a 'passwd' property instead. Just rename that variable and/or property and you should be good to go!
