### ISSUE TITLE
"Access denied for user ''@'localhost' (using password: NO)"

### ISSUE THREAD

**Issue by Vzotorp** [Pamblam/mysql-import#53]
I get this error when importing
using the correct mysql config for host/user/pass/db
```
Error: ER_ACCESS_DENIED_ERROR: Access denied for user ''@'localhost' (using password: NO)
    at Handshake.Sequence._packetToError (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Handshake.ErrorPacket (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/sequences/Handshake.js:123:18)
    at Protocol._parsePacket (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Protocol.handshake (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/protocol/Protocol.js:51:23)
    at Connection.connect (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql/lib/Connection.js:116:18)
    at /home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql-import/mysql-import.js:256:15
    at new Promise (<anonymous>)
    at Importer._connect (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql-import/mysql-import.js:250:10)
    at /home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql-import/mysql-import.js:130:16
    at new Promise (<anonymous>)
    at Importer.import (/home/catacomb/catacomb-online-server-dev/serverApp/node_modules/mysql-import/mysql-import.js:128:10)
    at /home/catacomb/catacomb-online-server-dev/serverApp/modules/sql.js:155:24 {
  code: 'ER_ACCESS_DENIED_ERROR',
  errno: 1045,
  sqlMessage: "Access denied for user ''@'localhost' (using password: NO)",
  sqlState: '28000',
  fatal: true
}
```

**Comment by Vzotorp** [comment]
also my app uses the same mysql config for other queries for the default node mysql module
and works fine

**Comment by vmartinetti** [comment]
Check this out:
#38

**Comment by Pamblam** [comment]
There's not enough info here to begin to troubleshoot the issue. According to the error message, you haven't passed it a username. All the tests are passing. If you want help troubleshooting your code, you need to, you know, share your code.
